import { Router } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { auth } from '../middleware/auth.js'
import type { AuthRequest } from '../types/auth.js'
const router = Router(); router.use(auth)
const id = z.string().min(1), propertyInput = z.object({ name: z.string().trim().min(2).max(120), address: z.string().max(250).optional(), phone: z.string().max(30).optional(), currency: z.string().max(5).default('INR'), rentDueDay: z.coerce.number().int().min(1).max(31).default(1) }), roomInput = z.object({ roomNumber: z.string().trim().min(1).max(30), floor: z.string().max(20).optional(), defaultRent: z.coerce.number().nonnegative(), status: z.enum(['vacant','occupied','archived']).optional(), notes: z.string().max(500).optional() }), tenantInput = z.object({ propertyId: id, roomId: id.optional(), name: z.string().trim().min(2).max(100), phone: z.string().trim().min(5).max(30), email: z.string().email().optional().or(z.literal('')), monthlyRent: z.coerce.number().positive(), securityDeposit: z.coerce.number().nonnegative().default(0), moveInDate: z.coerce.date().optional(), moveOutDate: z.coerce.date().optional(), status: z.enum(['active','inactive']).default('active'), notes: z.string().max(500).optional() })
const property = (userId: string) => prisma.property.findFirst({ where: { userId } })
router.get('/property', async (req: AuthRequest, res, next) => { try { res.json(await property(req.userId!)) } catch (e) { next(e) } })
router.post('/property', async (req: AuthRequest, res, next) => { try { const data = propertyInput.parse(req.body), old = await property(req.userId!); const result = old ? await prisma.property.update({ where: { id: old.id }, data }) : await prisma.property.create({ data: { ...data, userId: req.userId! } }); res.status(old ? 200 : 201).json(result) } catch (e) { next(e) } })
router.get('/rooms', async (req: AuthRequest, res, next) => { try { res.json(await prisma.room.findMany({ where: { property: { userId: req.userId! } }, orderBy: { roomNumber: 'asc' } })) } catch (e) { next(e) } })
router.post('/rooms', async (req: AuthRequest, res, next) => { try { const data = roomInput.parse(req.body), p = await property(req.userId!); if (!p) return res.status(404).json({ message: 'Create a property first' }); const room = await prisma.room.create({ data: { ...data, propertyId: p.id } }); res.status(201).json(room) } catch (e: any) { if (e.code === 'P2002') return res.status(409).json({ message: 'That room number already exists' }); next(e) } })
router.patch('/rooms/:roomId', async (req: AuthRequest, res, next) => { try { const data = roomInput.partial().parse(req.body), room = await prisma.room.findFirst({ where: { id: String(req.params.roomId), property: { userId: req.userId! } } }); if (!room) return res.status(404).json({ message: 'Room not found' }); res.json(await prisma.room.update({ where: { id: room.id }, data })) } catch (e) { next(e) } })
router.delete('/rooms/:roomId', async (req: AuthRequest, res, next) => { try { const room = await prisma.room.findFirst({ where: { id: String(req.params.roomId), property: { userId: req.userId! } } }); if (!room) return res.status(404).json({ message: 'Room not found' }); await prisma.room.delete({ where: { id: room.id } }); res.status(204).end() } catch (e) { next(e) } })
router.get('/tenants', async (req: AuthRequest, res, next) => { try { res.json(await prisma.tenant.findMany({ where: { userId: req.userId! }, include: { room: true }, orderBy: { name: 'asc' } })) } catch (e) { next(e) } })
router.post('/tenants', async (req: AuthRequest, res, next) => { try { const data = tenantInput.parse(req.body), p = await prisma.property.findFirst({ where: { id: data.propertyId, userId: req.userId! } }); if (!p) return res.status(404).json({ message: 'Property not found' }); if (data.roomId && !(await prisma.room.findFirst({ where: { id: data.roomId, propertyId: p.id } }))) return res.status(404).json({ message: 'Room not found' }); const tenant = await prisma.tenant.create({ data: { ...data, userId: req.userId!, email: data.email || null }, include: { room: true } }); if (tenant.roomId) await prisma.room.update({ where: { id: tenant.roomId }, data: { status: 'occupied' } }); res.status(201).json(tenant) } catch (e) { next(e) } })
router.patch('/tenants/:tenantId', async (req: AuthRequest, res, next) => { try { const data = tenantInput.partial().omit({ propertyId: true }).parse(req.body), tenant = await prisma.tenant.findFirst({ where: { id: String(req.params.tenantId), userId: req.userId! } }); if (!tenant) return res.status(404).json({ message: 'Tenant not found' }); const result = await prisma.tenant.update({ where: { id: tenant.id }, data: { ...data, email: data.email === '' ? null : data.email } }); if (tenant.roomId !== result.roomId) { if (tenant.roomId) await prisma.room.update({ where: { id: tenant.roomId }, data: { status: 'vacant' } }); if (result.roomId) await prisma.room.update({ where: { id: result.roomId }, data: { status: 'occupied' } }) } res.json(result) } catch (e) { next(e) } })
router.delete('/tenants/:tenantId', async (req: AuthRequest, res, next) => { try { const t = await prisma.tenant.findFirst({ where: { id: String(req.params.tenantId), userId: req.userId! } }); if (!t) return res.status(404).json({ message: 'Tenant not found' }); await prisma.tenant.update({ where: { id: t.id }, data: { status: 'inactive', moveOutDate: new Date() } }); if (t.roomId) await prisma.room.update({ where: { id: t.roomId }, data: { status: 'vacant' } }); res.status(204).end() } catch (e) { next(e) } })
router.get('/payments', async (req: AuthRequest, res, next) => { try { res.json(await prisma.payment.findMany({ where: { property: { userId: req.userId! } }, include: { tenant: true, room: true }, orderBy: { paymentDate: 'desc' } })) } catch (e) { next(e) } })
const paymentInput = z.object({ tenantId: id, amount: z.coerce.number().positive(), month: z.coerce.number().int().min(1).max(12), year: z.coerce.number().int().min(2000).max(2200), paymentDate: z.coerce.date().optional(), paymentMethod: z.enum(['Cash','UPI','Bank Transfer','Other']).default('Other'), transactionReference: z.string().max(100).optional(), notes: z.string().max(500).optional() })
router.post('/payments', async (req: AuthRequest, res, next) => { try { const data = paymentInput.parse(req.body), t = await prisma.tenant.findFirst({ where: { id: data.tenantId, userId: req.userId!, status: 'active' } }); if (!t) return res.status(404).json({ message: 'Tenant not found' }); const rent = await prisma.rentRecord.upsert({ where: { tenantId_month_year: { tenantId: t.id, month: data.month, year: data.year } }, create: { tenantId: t.id, propertyId: t.propertyId, roomId: t.roomId, month: data.month, year: data.year, rentAmount: t.monthlyRent }, update: {} }); res.status(201).json(await prisma.payment.create({ data: { ...data, tenantId: t.id, propertyId: t.propertyId, roomId: t.roomId, rentRecordId: rent.id } })) } catch (e) { next(e) } })
const period = (req: AuthRequest) => ({ month: Number(req.query.month || new Date().getMonth() + 1), year: Number(req.query.year || new Date().getFullYear()) })
router.get('/dashboard', async (req: AuthRequest, res, next) => { try { const { month, year } = period(req), p = await property(req.userId!); if (!p) return res.json({ property: null, summary: { totalRooms: 0, occupiedRooms: 0, activeTenants: 0, expected: 0, collected: 0, pending: 0 }, rent: [] }); const [rooms, tenants] = await Promise.all([prisma.room.findMany({ where: { propertyId: p.id, status: { not: 'archived' } } }), prisma.tenant.findMany({ where: { userId: req.userId!, propertyId: p.id, status: 'active' }, include: { room: true, rents: { where: { month, year }, include: { payments: true } } } })]); const rent = tenants.map(t => { const record = t.rents[0], expected = Number(record?.rentAmount ?? t.monthlyRent), paid = record?.payments.reduce((n, x) => n + Number(x.amount), 0) ?? 0; return { tenant: t, expected, paid, due: Math.max(expected - paid, 0), status: paid >= expected ? 'Paid' : paid ? 'Partial' : 'Pending' } }); const expected = rent.reduce((n, x) => n + x.expected, 0), collected = rent.reduce((n, x) => n + x.paid, 0); res.json({ property: p, summary: { totalRooms: rooms.length, occupiedRooms: rooms.filter(x => x.status === 'occupied').length, activeTenants: tenants.length, expected, collected, pending: Math.max(expected - collected, 0) }, rent }) } catch (e) { next(e) } })
router.get('/reports/monthly', async (req: AuthRequest, res, next) => { try { const { month, year } = period(req), payments = await prisma.payment.findMany({ where: { property: { userId: req.userId! }, month, year }, include: { tenant: true, room: true }, orderBy: { paymentDate: 'desc' } }), collected = payments.reduce((n, x) => n + Number(x.amount), 0); res.json({ month, year, collected, payments }) } catch (e) { next(e) } })
router.get('/reports/yearly', async (req: AuthRequest, res, next) => { try { const year = Number(req.query.year || new Date().getFullYear()), payments = await prisma.payment.findMany({ where: { property: { userId: req.userId! }, year } }); const monthly = Array.from({ length: 12 }, (_, i) => ({ month: i + 1, total: payments.filter(x => x.month === i + 1).reduce((n, x) => n + Number(x.amount), 0) })); res.json({ year, monthly, total: monthly.reduce((n, x) => n + x.total, 0) }) } catch (e) { next(e) } })
export default router
