import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Navigate, Route, Routes, Link, useNavigate } from 'react-router-dom'
import { LayoutDashboard, Users, DoorOpen, Receipt, LogOut, Plus, Wallet, X, ClipboardList, Settings } from 'lucide-react'
import { authApi, rentApi, propertyApi, roomApi, tenantApi, paymentApi, reportApi } from './services/api'
import './styles.css'

type Dashboard = { property: { name: string } | null; summary: { expected: number; collected: number; pending: number; occupiedRooms: number; totalRooms: number }; rent: Array<{ tenant: { id: string; name: string; room?: { roomNumber: string } }; expected: number; paid: number; due: number; status: string }> }
const money = (n: number) => `₹${n.toLocaleString('en-IN')}`

function Layout({ children, onLogout }: { children: React.ReactNode; onLogout: () => void }) { const navigate = useNavigate(); const logout = async () => { try { await authApi.logout() } finally { onLogout(); navigate('/login', { replace: true }) } }; return <div className="shell"><aside><div className="brand">Rentit</div><nav><Link to="/"><LayoutDashboard size={18}/>Dashboard</Link><Link to="/rent"><Receipt size={18}/>Rent</Link><Link to="/tenants"><Users size={18}/>Tenants</Link><Link to="/rooms"><DoorOpen size={18}/>Rooms</Link><Link to="/payments"><Wallet size={18}/>Payments</Link><Link to="/pending"><ClipboardList size={18}/>Pending</Link><Link to="/reports"><ClipboardList size={18}/>Reports</Link><Link to="/settings"><Settings size={18}/>Settings</Link></nav><button type="button" className="logout" onClick={logout}><LogOut size={18}/>Log out</button></aside><main>{children}</main></div> }
function Login({ onAuthenticated }: { onAuthenticated: (hasProperty?: boolean) => void }) { const [register, setRegister] = useState(false); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const navigate = useNavigate(); const submit = async (e: React.FormEvent) => { e.preventDefault(); try { if (register) { await authApi.register(form); onAuthenticated(false); navigate('/setup') } else { await authApi.login(form); onAuthenticated(); navigate('/') } } catch (err: any) { setError(err.response?.data?.message || 'Unable to continue') } }; return <div className="auth"><form onSubmit={submit}><div className="brand">Rentit</div><h1>{register ? 'Create your account' : 'Welcome back'}</h1><p>Secure rent management for property owners.</p>{register && <input placeholder="Full name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required /> }<input type="email" placeholder="Email address" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required /><input type="password" placeholder="Password (8+ characters)" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} minLength={8} required />{error && <div className="error">{error}</div>}<button className="primary">{register ? 'Register' : 'Sign in'}</button><button type="button" className="link" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New here? Create an account'}</button></form></div> }
function SetupPage({ onComplete }: { onComplete: () => void }) { const [form, setForm] = useState({ name: '', ownerName: '', phone: '', currency: 'INR', rentDueDay: '1' }); const [error, setError] = useState(''); const submit = async (event: React.FormEvent) => { event.preventDefault(); try { await propertyApi.save({ name: form.name, phone: form.phone, currency: form.currency, rentDueDay: Number(form.rentDueDay) }); onComplete() } catch (err: any) { setError(err.response?.data?.message || 'Unable to save property details') } }; return <div className="auth"><form onSubmit={submit}><h1>Welcome to Rentit</h1><p>Set up your property profile</p><label>Property Name</label><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="e.g. Greenview Apartments" required /><label>Owner Name</label><input value={form.ownerName} onChange={e => setForm({ ...form, ownerName: e.target.value })} placeholder="Your name" required /><label>Phone</label><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="+91 98765 43210" required /><label>Currency</label><select value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value })}><option value="INR">₹ Indian Rupee</option><option value="USD">$ US Dollar</option><option value="EUR">€ Euro</option></select><label>Default Rent Due Day</label><input type="number" min="1" max="31" value={form.rentDueDay} onChange={e => setForm({ ...form, rentDueDay: e.target.value })} required />{error && <div className="error">{error}</div>}<button className="primary">Continue</button></form></div> }
function DashboardPage() { const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(''); useEffect(() => { rentApi.dashboard().then(r => setData(r.data)).catch(() => setError('Could not load your dashboard')) }, []); if (error) return <div className="empty error">{error}</div>; if (!data) return <div className="loading">Loading dashboard…</div>; return <><header><div><h1>Dashboard</h1><p>{data.property?.name || 'Set up your property to get started'}</p></div><Link className="primary small" to="/payments"><Plus size={16}/>Record payment</Link></header><section className="cards"><Metric label="Expected rent" value={money(data.summary.expected)} /><Metric label="Collected" value={money(data.summary.collected)} tone="green" /><Metric label="Pending" value={money(data.summary.pending)} tone="orange" /><Metric label="Occupied rooms" value={`${data.summary.occupiedRooms}/${data.summary.totalRooms}`} /></section><section className="panel"><div className="panel-head"><h2>Rent status</h2><span>This month</span></div>{data.rent.length === 0 ? <div className="empty">No active tenants yet. Add your first tenant to begin.</div> : <div className="table"><div className="row head"><span>Tenant</span><span>Room</span><span>Rent</span><span>Paid</span><span>Due</span><span>Status</span></div>{data.rent.map(row => <div className="row" key={row.tenant.id}><strong>{row.tenant.name}</strong><span>{row.tenant.room?.roomNumber || 'Unassigned'}</span><span>{money(row.expected)}</span><span>{money(row.paid)}</span><span>{money(row.due)}</span><span className={`badge ${row.status.toLowerCase()}`}>{row.status}</span></div>)}</div>}</section></> }
function RentListPage({ pendingOnly = false }: { pendingOnly?: boolean }) { const [data, setData] = useState<Dashboard | null>(null); useEffect(() => { rentApi.dashboard().then(r => setData(r.data)) }, []); if (!data) return <div className="loading">Loading…</div>; const rows = pendingOnly ? data.rent.filter(row => row.due > 0) : data.rent; return <><header><div><h1>{pendingOnly ? 'Pending Rent' : 'Rent'}</h1><p>{pendingOnly ? 'Tenants with outstanding balances.' : 'Track rent for the current month.'}</p></div></header><section className="panel"><div className="table"><div className="row head"><span>Tenant</span><span>Room</span><span>Expected</span><span>Paid</span><span>Due</span><span>Status</span><span>Action</span></div>{rows.length ? rows.map(row => <div className="row" key={row.tenant.id}><strong>{row.tenant.name}</strong><span>{row.tenant.room?.roomNumber || 'Unassigned'}</span><span>{money(row.expected)}</span><span>{money(row.paid)}</span><span>{money(row.due)}</span><span className={`badge ${row.status.toLowerCase()}`}>{row.status}</span><Link className="primary small" to={`/payments?tenantId=${row.tenant.id}`}>Record payment</Link></div>) : <div className="empty">No records found.</div>}</div></section></> }
function ReportsPage() { const [data, setData] = useState<any>(null); useEffect(() => { reportApi.monthly().then(({ data }) => setData(data)).catch(() => setData({ error: true })) }, []); if (!data) return <div className="loading">Loading reports…</div>; return <><header><div><h1>Reports</h1><p>Collection performance for the current month.</p></div></header><section className="cards"><Metric label="Collected" value={money(data.total || 0)} tone="green" /><Metric label="Month" value={`${data.month}/${data.year}`} /></section><section className="panel"><div className="panel-head"><h2>Payment history</h2><span>{data.payments?.length || 0} payments</span></div>{data.payments?.length ? data.payments.map((payment: any) => <div className="row" key={payment.id}><strong>{payment.tenant?.name || 'Tenant'}</strong><span>{payment.paymentMethod}</span><span>{money(Number(payment.amount))}</span><span>{new Date(payment.paymentDate).toLocaleDateString()}</span></div>) : <div className="empty">No payments recorded yet.</div>}</section></> }
function SettingsPage() { const [form, setForm] = useState({ name: '', phone: '', currency: 'INR', rentDueDay: 1 }); const [saved, setSaved] = useState(false); useEffect(() => { propertyApi.get().then(({ data }) => data && setForm({ name: data.name, phone: data.phone || '', currency: data.currency || 'INR', rentDueDay: data.rentDueDay || 1 })) }, []); const submit = async (event: React.FormEvent) => { event.preventDefault(); await propertyApi.save({ ...form, rentDueDay: Number(form.rentDueDay) }); setSaved(true) }; return <><header><div><h1>Settings</h1><p>Update your property profile.</p></div></header><form className="panel modal" onSubmit={submit}><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Property name" required /><input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="Phone" /><select value={form.currency} onChange={e => setForm({ ...form, currency: e.target.value })}><option value="INR">₹ Indian Rupee</option><option value="USD">$ US Dollar</option></select><input type="number" min="1" max="31" value={form.rentDueDay} onChange={e => setForm({ ...form, rentDueDay: Number(e.target.value) })} /><button className="primary">Save changes</button>{saved && <div className="error">Settings saved.</div>}</form></> }
function Metric({ label, value, tone = '' }: { label: string; value: string; tone?: string }) { return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></div> }
function SimplePage({ title, icon: Icon }: { title: string; icon: typeof Users }) {
  const [open, setOpen] = useState(false)
  const [propertyId, setPropertyId] = useState('')
  const [tenants, setTenants] = useState<Array<{ id: string; name: string; roomId?: string }>>([])
  const [rooms, setRooms] = useState<Array<{ id: string; roomNumber: string }>>([])
  const [paymentTenantId] = useState(() => new URLSearchParams(window.location.search).get('tenantId') || '')
  const [records, setRecords] = useState<any[]>([])
  const [error, setError] = useState('')
  useEffect(() => {
    propertyApi.get().then(({ data }) => setPropertyId(data?.id || '')).catch(() => undefined)
    roomApi.list().then(({ data }) => setRooms(data)).catch(() => undefined)
    if (title === 'Payments') tenantApi.list().then(({ data }) => setTenants(data)).catch(() => undefined)
    if (title === 'Rooms') tenantApi.list().then(({ data }) => setTenants(data)).catch(() => undefined)
    if (title === 'Rooms') roomApi.list().then(({ data }) => setRecords(data)).catch(() => undefined)
    if (title === 'Tenants') tenantApi.list().then(({ data }) => setRecords(data)).catch(() => undefined)
    if (title === 'Payments') paymentApi.list().then(({ data }) => setRecords(data)).catch(() => undefined)
  }, [title])
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setError('')
    const data = Object.fromEntries(new FormData(event.currentTarget).entries())
    try {
      let created
      if (title === 'Rooms') created = await roomApi.create({ ...data, propertyId, defaultRent: Number(data.defaultRent) })
      if (title === 'Tenants') created = await tenantApi.create({ ...data, propertyId, roomId: data.roomId || undefined, monthlyRent: Number(data.monthlyRent), securityDeposit: Number(data.securityDeposit || 0) })
      if (title === 'Payments') created = await paymentApi.create({ ...data, amount: Number(data.amount), month: Number(data.month), year: Number(data.year) })
      if (created) setRecords(current => [...current, created.data])
      setOpen(false)
    } catch (err: any) { setError(err.response?.data?.message || 'Unable to save this record') }
  }
  const fields = title === 'Rooms' ? <><input name="roomNumber" placeholder="Room number" required /><input name="floor" placeholder="Floor" /><input name="defaultRent" type="number" placeholder="Default rent" min="0" required /></> : title === 'Tenants' ? <><input name="name" placeholder="Tenant name" required /><input name="phone" placeholder="Phone" required /><select name="roomId" defaultValue=""><option value="">No room assigned</option>{rooms.map(room => <option key={room.id} value={room.id}>Room {room.roomNumber}</option>)}</select><input name="monthlyRent" type="number" placeholder="Monthly rent" min="1" required /><input name="securityDeposit" type="number" placeholder="Security deposit" min="0" /></> : <><select name="tenantId" defaultValue={paymentTenantId} required><option value="">Select tenant</option>{tenants.map(tenant => <option key={tenant.id} value={tenant.id}>{tenant.name}</option>)}</select><input name="amount" type="number" placeholder="Amount" min="1" required /><input name="month" type="number" placeholder="Month (1-12)" min="1" max="12" required /><input name="year" type="number" defaultValue={new Date().getFullYear()} min="2000" max="2200" required /><select name="paymentMethod" defaultValue="Other"><option>Cash</option><option>UPI</option><option>Bank Transfer</option><option>Other</option></select></>
  return <><header><div><h1>{title}</h1><p>Manage this area from your Rentit workspace.</p></div><button type="button" className="primary small" onClick={() => setOpen(true)}><Plus size={16}/>Add {title.slice(0, -1)}</button></header><div className={records.length ? 'panel' : 'panel empty'}>{records.length ? <div className="table"><div className="row head"><span>{title === 'Rooms' ? 'Room' : title.slice(0, -1)}</span><span>{title === 'Rooms' ? 'Floor' : title === 'Tenants' ? 'Room / Phone' : 'Details'}</span><span>{title === 'Rooms' ? 'Rent' : 'Status'}</span>{title === 'Rooms' && <span>Status</span>}</div>{records.map(record => { const assigned = title === 'Rooms' ? tenants.find(tenant => tenant.roomId === record.id) : null; return <div className="row" key={record.id}><strong>{record.roomNumber || record.name || record.tenant?.name}</strong><span>{title === 'Tenants' ? `Room ${record.room?.roomNumber || 'Unassigned'} · ${record.phone || '—'}` : record.floor || record.paymentMethod || record.phone || '—'}</span><span>{title === 'Rooms' ? `₹${Number(record.defaultRent).toLocaleString('en-IN')}` : record.status || 'Recorded'}</span>{title === 'Rooms' && <span className={`badge ${assigned ? 'paid' : 'pending'}`}>{assigned ? assigned.name : 'Vacant'}</span>}</div> })}</div> : <><Icon size={32}/><h2>No records yet</h2><p>Connect the API and add your first record to see it here.</p></>}</div>{open && <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.currentTarget === event.target) setOpen(false) }}><form className="modal" onSubmit={submit}><button type="button" className="modal-close" aria-label="Close" onClick={() => setOpen(false)}><X size={18}/></button><h2>Add {title.slice(0, -1)}</h2>{fields}{error && <div className="error">{error}</div>}<button className="primary" type="submit">Save</button></form></div>}</>
}
function App() { const [auth, setAuth] = useState<boolean | null>(null); const [hasProperty, setHasProperty] = useState<boolean | null>(null); useEffect(() => { authApi.me().then(() => setAuth(true)).catch(() => setAuth(false)) }, []); useEffect(() => { if (auth) propertyApi.get().then(({ data }) => setHasProperty(Boolean(data))).catch(() => setHasProperty(false)) }, [auth]); if (auth === null || (auth && hasProperty === null)) return <div className="loading">Loading…</div>; return <Routes><Route path="/login" element={auth ? <Navigate to={hasProperty ? '/' : '/setup'}/> : <Login onAuthenticated={hasProperty => { setAuth(true); setHasProperty(hasProperty ?? null) }}/>} /><Route path="/setup" element={auth ? (hasProperty ? <Navigate to="/"/> : <SetupPage onComplete={() => setHasProperty(true)}/>) : <Navigate to="/login"/>}/><Route path="/*" element={auth ? (hasProperty ? <Layout onLogout={() => { setAuth(false); setHasProperty(null) }}><Routes><Route path="/" element={<DashboardPage/>}/><Route path="/rent" element={<RentListPage/>}/><Route path="/tenants" element={<SimplePage title="Tenants" icon={Users}/>}/><Route path="/rooms" element={<SimplePage title="Rooms" icon={DoorOpen}/>}/><Route path="/payments" element={<SimplePage title="Payments" icon={Wallet}/>}/><Route path="/pending" element={<RentListPage pendingOnly/>}/><Route path="/reports" element={<ReportsPage/>}/><Route path="/settings" element={<SettingsPage/>}/></Routes></Layout> : <Navigate to="/setup"/>) : <Navigate to="/login"/>}/></Routes> }
createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)
